version: "3.9"

services:
  backend:
    build: ./src/backend
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build: ./src/frontend
    ports:
      - "3000:3000"
    restart: always
